blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, not_activity_posts

app_name = BlogConfig.name

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog_not_activity/', not_activity_posts, name='blog_not_activity'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Статья')
    image = models.ImageField(upload_to='blog/', blank=True, null=True)
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    is_published = models.BooleanField(default=False, verbose_name='Опубликованно')

    def __str__(self):
        return f'{self.title} - {self.views} - {self.pub_date}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/forms.py
from django import forms

from blog.models import Blog
from main.forms import StyleMixin


class BlogForm(StyleMixin):
    """Форма для блога"""
    class Meta:
        model = Blog
        exclude = ('views',)

blog/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.forms import BlogForm
from blog.models import Blog
from blog.services import get_cache_posts_from_blog


class UserPassesMixin(UserPassesTestMixin):
    """Класс миксин для проверки состоит ли пользователь в группе content_manager"""
    def test_func(self):
        user = self.request.user
        if user.groups.filter(name='content_manager').exists() or user.is_superuser:
            return True
        else:
            return False


class BlogListView(ListView):
    """Класс для отображения статей блога"""
    model = Blog

    def get_context_data(self, **kwargs):
        """Передает конекст в шаблон"""
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = get_cache_posts_from_blog()
        return context_data


@user_passes_test(lambda u: u.groups.filter(name='content_manager').exists())
def not_activity_posts(request):
    """Изменение статуса публикации статьи"""
    post = Blog.objects.filter(is_published=False).order_by('-pub_date')
    return render(request, 'blog/blog_list.html', {'object_list': post})


class BlogCreateView(LoginRequiredMixin, UserPassesMixin, CreateView):
    """Класс для создания статьи блога"""
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')


class BlogDetailView(LoginRequiredMixin, DetailView):
    """Класс для отображения конкретной статьи"""
    model = Blog

    def get_object(self, queryset=None):
        """Функция учитывает просмотры данной статьи. Учитывает только просмотры пользователей и не
        учитывает просмотры персонала"""
        user = self.request.user
        blog = Blog.objects.get(id=self.kwargs['pk'])
        if not user.is_staff:
            blog.views += 1
            blog.save()

        return blog


class BlogUpdateView(LoginRequiredMixin, UserPassesMixin, UpdateView):
    """Класс для изменения статьи блога"""
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')


class BlogDeleteView(LoginRequiredMixin, UserPassesMixin, DeleteView):
    """Класс для удаления статьи блога"""
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col">
            <div class="card-header">
                Удаление статьи
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить? {{ object.title}}</p>
                <button type="submit"  class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'blog:blog_detail' object.pk %}">Отмена</a>
            </div>
        </div>
    </form>


{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% block content %}
    {% if perms.blog.change_blog %}
        <p class="d-inline-flex gap-1">
            <a class="btn btn-success" href="{% url 'blog:blog_update' object.pk %}">
                Редактировать статью
            </a>
        </p>
        <p class="d-inline-flex gap-1">
            <a class="btn btn-danger" href="{% url 'blog:blog_delete' object.pk %}">
                Удалить статью
            </a>
        </p>
    {% endif %}

    <div class="col-12 text-center">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
            <div class="card-header py-3 text-bg-primary border-primary">
                <h4 class="my-0 fw-normal">{{ object.title }}</h4>
            </div>
            <div class="card-body">
                <img src="/media/{{ object.image }}" alt="Card image app">
                <p>{{ object.content }}</p>

            </div>
            <p>Кол-во просмотров - {{ object.views }}</p>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}


{% block content %}

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">Создать статью</div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
{#                        <input type="hidden" name="boat_id" value="{{ boat.pk }}">#}
                        {{ form.as_p }}
                        {% if object %}
                            <button type="submit"  class="btn btn-success">Изменить</button>
                        {% else %}
                            <button type="submit" class="btn btn-success">Создать</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}


{% block content %}
    <div class="row text-center">
        {% if perms.blog.add_blog %}
            <p class="d-inline-flex gap-1">
                <a class="btn btn-success" href="{% url 'blog:blog_create' %}">
                    Добавить статью
                </a>
            </p>
            <p class="d-inline-flex gap-1 ml-4">
                <a class="btn btn-warning" href="{% url 'blog:blog_not_activity' %}">
                    Не активные статьи
                </a>
            </p>
        {% endif %}
        {% for object in object_list %}
            <div class="col-12">
                <div class="card mb-4 rounded-3 shadow-sm border-primary">
                    <div class="card-header py-3 text-bg-primary border-primary">
                        <h4 class="my-0 fw-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <p><img src="/media/{{ object.image }}" alt="Card image app"></p>
                        <p>{{ object.content | truncatechars:300 }}</p>
                        <a class="btn btn-primary" href="{% url 'blog:blog_detail' object.pk %}">К статье</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}