blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, not_activity_posts

app_name = BlogConfig.name

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog_not_activity/', not_activity_posts, name='blog_not_activity'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import IndexView, ClientCreateView, ClientListView, ClientDetailView, ClientUpdateView, \
    ClientDeleteView, MailDeliverySettingsListView, MailDeliverySettingsCreateView, MailDeliverySettingsDetailView, \
    MailDeliverySettingsUpdateView, MailDeliverySettingsDeleteView, LogListView, newsletter_activity

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(60)(IndexView.as_view()), name='index'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('newsletter_list/', MailDeliverySettingsListView.as_view(), name='newsletter_list'),
    path('newsletter_create/', MailDeliverySettingsCreateView.as_view(), name='newsletter_create'),
    path('newsletter_detail/<int:pk>', MailDeliverySettingsDetailView.as_view(), name='newsletter_detail'),
    path('newsletter_update/<int:pk>', MailDeliverySettingsUpdateView.as_view(), name='newsletter_update'),
    path('newsletter_delete/<int:pk>', MailDeliverySettingsDeleteView.as_view(), name='newsletter_delete'),
    path('log_list/<int:pk>', LogListView.as_view(), name='log_list'),
    path('activate/<int:pk>', newsletter_activity, name='activate'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserRegistrationView, UserProfileView, UserVerifyView, UserDetailView, UserListView, \
    user_activity, UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('verify/', UserVerifyView.as_view(), name='verify'),
    path('detail/', UserDetailView.as_view(), name='detail'),
    path('view_users/', UserListView.as_view(), name='view_users'),
    path('user_active/<int:pk>', user_activity, name='user_active'),
    path('user_delete/', UserDeleteView.as_view(), name='user_delete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='email')
    phone_number = models.CharField(max_length=15, verbose_name='Телефон', null=True, blank=True)
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='аватар', blank=True, null=True)

    verify_key = models.CharField(max_length=128, verbose_name='Ключ верификации', null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from main.forms import StyleMixin
from users.models import User


class UserRegistrationForm(UserCreationForm):
    """Класс формы для отображения полей при регистрации пользователя"""
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserProfileForm(UserChangeForm):
    """Класс формы для изменения полей пользователя"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone_number', 'avatar',)

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView, DetailView, ListView, DeleteView

from users.forms import UserRegistrationForm, UserProfileForm
from users.models import User
from users.services import send_verify_key_to_email, generate_verify_key


class ManagerTestMixin(UserPassesTestMixin):
    """Миксин для проверки пользователя, является ли он менеджером или суперпользователем"""

    def test_func(self):
        user = self.request.user
        if user.groups.filter(name='manager').exists() or user.is_superuser:
            return True
        else:
            return False


class UserRegistrationView(CreateView):
    """Класс для регистрации пользователя."""
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:verify')

    def form_valid(self, form):
        """Прирегистрации пользователя отправляется сгенерированный ключ верификации"""
        verify_key = generate_verify_key()
        new_user = form.save()
        new_user.verify_key = verify_key
        new_user.save()
        send_verify_key_to_email(new_user.email, verify_key)

        return super().form_valid(form)


class UserProfileView(LoginRequiredMixin, UpdateView):
    """Класс для изменения данных пользователя"""
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:detail')

    def get_object(self, queryset=None):
        return self.request.user


class UserVerifyView(TemplateView):
    """Класс для верификации пользователя по введенному ключу"""
    template_name = 'users/verify.html'

    @staticmethod
    def post(request, *args, **kwargs):
        """Функция проверки ввел ли пользователь верный ключ верификации отправленный на его email"""
        verify_key = request.POST.get('verify_key')
        user = User.objects.filter(verify_key=verify_key).first()
        if user is not None and user.verify_key == verify_key:
            user.is_active = True
            user.save()
            return redirect('users:login')
        return render(request, 'users/verify_err.html')


class UserDetailView(LoginRequiredMixin, DetailView):
    """Класс для просмотра информации о пользователи"""
    model = User

    def get_object(self, queryset=None):
        """Функция для определения какой пользователь пытается изменить данные"""
        user = self.request.user
        if user.groups.filter(name='manager').exists():
            return User.objects.filter(email=self.request.GET.get('email')).first()
        return user


class UserListView(ManagerTestMixin, ListView):
    """Класс для отображения списка пользователей"""
    model = User

    def get_context_data(self, **kwargs):
        """Функция которая передает в контекст только пользователей не являющихся персоналом или
        суперпользователем"""
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = User.objects.filter(is_staff=False)
        return context_data


def user_activity(request, pk):
    """Функция для изменения поля is_active в True или False. Доступна только пользователю из группы manager"""
    user = get_object_or_404(User, pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True

    user.save()

    return redirect(reverse('users:view_users'))


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Класс для удаления пользователя из системы. Доступна только суперпользователю"""
    model = User
    success_url = reverse_lazy('main:index')

    def test_func(self):
        """Функция для проверки является ли пользователь суперпользователем"""
        user = self.request.user
        if user.is_superuser:
            return True
        else:
            return False

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Вход</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/registration.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col">
            <div class="card-header">
                Удаление пользователя
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить? {{ object.full_name}}</p>
                <button type="submit"  class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'main:index'%}">Отмена</a>
            </div>
        </div>
    </form>


{% endblock %}

users/templates/users/user_detail.html
{% extends 'main/base.html' %}
{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">ФИО</th>
            <th scope="col">email</th>
            <th scope="col">Телефон</th>
            <th scope="col">Фото</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ object.first_name }} {{ object.last_name }}</td>
            <td>{{ object.email }}</td>
            {% if object.phone_number %}
                <td>{{ object.phone_number }}</td>
            {% else %}
                <td>Не указан</td>
            {% endif %}
            {% if object.avatar %}
                <td><img src="/media/{{ object.avatar }}" alt="Card image app"></td>
            {% else %}
                <td>Фото отсутствует</td>
            {% endif %}
            {% if not user.is_staff %}
                <td><a href="{% url 'users:profile' %}">Изменить</a></td>
            {% else %}
                <td><a href="{% url 'users:user_delete' %}">Удалить</a></td>
            {% endif %}
        </tr>
        </tbody>
    </table>

{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Мой профиль
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                </div>
{#                <div class="card-footer">#}
{#                    <a href="#" class="btn btn-danger">Сгенерировать пароль</a>#}
{#                </div>#}
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}
{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ФИО</th>
            <th scope="col">email</th>
            <th scope="col">Телефон</th>
            <th scope="col">Статус</th>
            <th scope="col">Изменить статус</th>

        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>

                <th scope="row">{{ forloop.counter }}</th>
                {% if object.get_full_name %}
                    <td>{{ object.get_full_name }}</td>
                {% else %}
                    <td>Не указанно</td>
                {% endif %}

                <td>{{ object.email }}</td>

                {% if object.phone_number %}
                    <td>{{ object.phone_number }}</td>
                {% else %}
                    <td>Не указан</td>
                {% endif %}

                {% if object.is_active %}
                    <td>Активный</td>
                {% else %}
                    <td>Деактивирован</td>
                {% endif %}

                {% if object.is_active %}
                    <td><a class="btn btn-danger"
                           href="{% url 'users:user_active' object.pk %}">Деактивировать</a></td>
                {% else %}
                    <td><a class="btn btn-success"
                           href="{% url 'users:user_active' object.pk %}">Активиоровать</a></td>
                {% endif %}
                {% if user.is_superuser %}
                    <td><a class="btn btn-success"
                           href="{% url 'users:user_delete' object.pk %}">Удалить</a></td>
                {% endif %}

            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

users/templates/users/verify.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form class='row' method="post" enctype="multipart/form-data">
            <div class="col-4"></div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            Введите код
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}

                        <input type="text" name="verify_key" class="form-control" id="ver_code" required>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/verify_err.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form class='row' method="post" enctype="multipart/form-data">
            <div class="col-4"></div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            Вы ввели не правильный код
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}

                        <input type="text" name="verify_key" class="form-control" id="ver_code" required>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}