blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, not_activity_posts

app_name = BlogConfig.name

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog_not_activity/', not_activity_posts, name='blog_not_activity'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import IndexView, ClientCreateView, ClientListView, ClientDetailView, ClientUpdateView, \
    ClientDeleteView, MailDeliverySettingsListView, MailDeliverySettingsCreateView, MailDeliverySettingsDetailView, \
    MailDeliverySettingsUpdateView, MailDeliverySettingsDeleteView, LogListView, newsletter_activity

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(60)(IndexView.as_view()), name='index'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('newsletter_list/', MailDeliverySettingsListView.as_view(), name='newsletter_list'),
    path('newsletter_create/', MailDeliverySettingsCreateView.as_view(), name='newsletter_create'),
    path('newsletter_detail/<int:pk>', MailDeliverySettingsDetailView.as_view(), name='newsletter_detail'),
    path('newsletter_update/<int:pk>', MailDeliverySettingsUpdateView.as_view(), name='newsletter_update'),
    path('newsletter_delete/<int:pk>', MailDeliverySettingsDeleteView.as_view(), name='newsletter_delete'),
    path('log_list/<int:pk>', LogListView.as_view(), name='log_list'),
    path('activate/<int:pk>', newsletter_activity, name='activate'),
]

main/models.py
from django.db import models

from users.models import User


class Client(models.Model):
    full_name = models.CharField(max_length=250, verbose_name='Полное имя')
    email = models.EmailField(max_length=150, verbose_name='эл.почта')
    comment = models.TextField(verbose_name='Комментарий', blank=True, null=True)

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Пользователь', blank=True, null=True)

    def __str__(self):
        return f'{self.full_name} ({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class MailDeliverySettings(models.Model):
    CREATE = 'Создана'
    LAUNCHED = 'Запущена'
    COMPLETED = 'Завершена'

    STATUS_CHOICE = [
        (CREATE, 'Создана'),
        (LAUNCHED, 'Запущена'),
        (COMPLETED, 'Завершена')
    ]

    HOUR = 'Раз в час'
    DAY = 'Раз в день'
    WEEK = 'Раз в неделю'

    PERIODICITY_CHOICE = [
        (HOUR, 'Раз в час'),
        (DAY, 'Раз в день'),
        (WEEK, 'Раз в неделю')
    ]
    name = models.CharField(max_length=150, verbose_name='Название рассылки', blank=True, null=True)
    time_start = models.DateTimeField(verbose_name='Начало рассылки')
    time_stop = models.DateTimeField(verbose_name='Окончание рассылки')
    periodicity = models.CharField(max_length=70, choices=PERIODICITY_CHOICE, verbose_name='Периодичность рассылки')
    status = models.CharField(max_length=70, default=CREATE, choices=STATUS_CHOICE, verbose_name='Статус')
    subject = models.CharField(max_length=255, verbose_name='Тема письма')
    message = models.TextField(verbose_name='Тело письма')

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', blank=True, null=True)

    def __str__(self):
        return f'{self.status} - ({self.subject})'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class Log(models.Model):
    SUCCESS = 'Успешно'
    FAIL = 'Ошибка отправки'

    OK = 'ok'

    ATTEMPT_STATUS = [
        (SUCCESS, 'Успешно'),
        (FAIL, 'Ошибка отправки')
    ]

    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата попытки')
    status = models.CharField(default=SUCCESS, choices=ATTEMPT_STATUS, max_length=50, verbose_name='Статус попытки')
    answer = models.TextField(default=OK, verbose_name='Ответ сервера')

    newsletter = models.ForeignKey(MailDeliverySettings, on_delete=models.CASCADE, verbose_name='Рассылка')

    def __str__(self):
        return f'{self.status} - ({self.answer})'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

main/forms.py
from django import forms
from django.utils import timezone

from main.models import Client, MailDeliverySettings


class StyleMixin(forms.ModelForm):
    """Класс миксин для общего стиля форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleMixin):
    """Форма клиента"""

    class Meta:
        model = Client
        exclude = ('user',)


class MailDeliverySettingsForm(StyleMixin):
    """Форма рассылки"""

    class Meta:
        model = MailDeliverySettings
        exclude = ('status', 'log', 'user')

    def clean_time_start(self):
        """Проверяет что время начала рассылки больше текущего времени"""
        cleaned_data = self.cleaned_data['time_start']
        now = timezone.localtime(timezone.now())
        if cleaned_data < now:
            raise forms.ValidationError('Время начала не может быть меньше текущего времени')
        return cleaned_data

    def clean_time_stop(self):
        """Проверяет что время окончания рассылки больше текущего времени"""
        cleaned_data = self.cleaned_data['time_stop']
        now = timezone.localtime(cleaned_data)
        if cleaned_data < now:
            raise forms.ValidationError('Время окончания не может быть меньше текущего времени')
        return cleaned_data

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView, DeleteView

from main.forms import ClientForm, MailDeliverySettingsForm
from main.models import Client, MailDeliverySettings, Log
from main.services import get_context_data_for_user, get_context_data_for_manager


class UserPassesMixin(UserPassesTestMixin):
    """Миксин для проверки является ли пользователь владельцем рассылки и не заблокирован ли он в системе"""

    def test_func(self):
        user = self.request.user
        newsletter = self.get_object()
        if newsletter.user == user and user.is_active:
            return True
        else:
            return False


class IndexView(TemplateView):
    """Класс для отображения главной страницы"""
    template_name = 'main/index.html'
    model = Client

    def get_context_data(self, **kwargs):
        """Функция для передачи контекста в шаблон"""
        context_data = super().get_context_data()
        context_data['title'] = 'Рассылочка'
        user = self.request.user
        if user.is_authenticated and not user.is_staff:
            context_data.update(get_context_data_for_user(user))
        elif user.is_staff:
            context_data.update(get_context_data_for_manager())
        return context_data


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Класс для создания клиента сервиса"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        """Функция принимает форму клиента и присваивает его пользователю создавшего его"""
        new_client = form.save()
        new_client.user = self.request.user
        new_client.save()
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    """Класс для отображения клиентов сервиса"""
    model = Client

    def get_context_data(self, **kwargs):
        """Передает контекст и проверяет является пользователь авторизованным и или персоналом"""
        context_data = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated and not user.is_staff:
            context_data['object_list'] = Client.objects.filter(user_id=user)
        elif user.is_staff:
            context_data['object_list'] = Client.objects.all()
        return context_data


class ClientDetailView(LoginRequiredMixin, UserPassesMixin, DetailView):
    """Класс для отображения информации о клиенте"""
    model = Client


class ClientUpdateView(LoginRequiredMixin, UserPassesMixin, UpdateView):
    """Класс для изменения данных о клиенте"""
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        """Функция для перенаправления пользователя на страницу клиента после изменения"""
        return reverse('main:client_detail', args=[self.kwargs.get('pk')])


class ClientDeleteView(LoginRequiredMixin, UserPassesMixin, DeleteView):
    """Класс для удаления клиента из системы"""
    model = Client
    success_url = reverse_lazy('main:client_list')


class MailDeliverySettingsListView(LoginRequiredMixin, ListView):
    """Класс для отображения всех рассылок пользователя"""
    model = MailDeliverySettings

    def get_context_data(self, **kwargs):
        """Передает контекст в шаблон"""
        context_data = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_staff:
            context_data['object_list'] = MailDeliverySettings.objects.all()
        else:
            context_data['object_list'] = MailDeliverySettings.objects.filter(user_id=user)
        return context_data


class MailDeliverySettingsCreateView(LoginRequiredMixin, CreateView):
    """Класс для создания рассылки"""
    model = MailDeliverySettings
    form_class = MailDeliverySettingsForm
    success_url = reverse_lazy('main:newsletter_list')

    def form_valid(self, form):
        """Функция принимает форму рассылки и присваивает ее авторизованному пользователю"""
        new_newsletter = form.save()
        new_newsletter.user = self.request.user
        new_newsletter.save()
        return super().form_valid(form)


class MailDeliverySettingsDetailView(LoginRequiredMixin, UserPassesMixin, DetailView):
    """Класс для отображения данных о рассылки"""
    model = MailDeliverySettings

    def test_func(self):
        """Тестовая функция для проверки владельза рассылки или персонала"""
        user = self.request.user
        newsletter = self.get_object()
        if user.is_staff or newsletter.user == user:
            return True
        else:
            return False


class MailDeliverySettingsUpdateView(LoginRequiredMixin, UserPassesMixin, UpdateView):
    """Класс для изменения рассылки"""
    model = MailDeliverySettings
    permission_required = 'main.change_maildeliverysettings'
    form_class = MailDeliverySettingsForm

    def get_success_url(self):
        """Функция перенаправления после создания на страницу созданной рассылки"""
        return reverse('main:newsletter_detail', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        """Функция для изменения статуса после создания"""
        self.object = super().get_object(queryset)
        now = timezone.localtime(timezone.now())
        if self.object.time_start > now:
            self.object.status = MailDeliverySettings.CREATE
        return self.object


class MailDeliverySettingsDeleteView(LoginRequiredMixin, UserPassesMixin, DeleteView):
    """Класс для удаления рассылки"""
    model = MailDeliverySettings
    success_url = reverse_lazy('main:newsletter_list')


class LogListView(ListView):
    """Класс для просмотра логов рассылки"""
    model = Log

    def get_queryset(self):
        """Функция для выбора логов из БД для конкретной рассылки"""
        queryset = super().get_queryset()
        queryset = queryset.filter(newsletter_id=self.kwargs.get('pk'))
        return queryset


def newsletter_activity(request, pk):
    """Функция для изменение статуса рассылки (доступна администратору)"""
    newsletter = get_object_or_404(MailDeliverySettings, pk=pk)
    if newsletter.status in [MailDeliverySettings.CREATE, MailDeliverySettings.LAUNCHED]:
        newsletter.status = MailDeliverySettings.COMPLETED
    else:
        newsletter.status = MailDeliverySettings.CREATE

    newsletter.save()

    return redirect(reverse('main:newsletter_list'))

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>{{ title }}</title>


    <link rel="stylesheet" href="{% static 'css/docsearch.css' %}">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
</head>
<body>

<div class="container">
    <header>
        {% include 'main/includes/inc_header.html' %}
    </header>

    <main class="container">


            {% block content %}

            {% endblock %}


    </main>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-body-secondary">&copy; 2017–{% now 'Y' %}</small>
            </div>
        </div>
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>

</body>
</html>

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col">
            <div class="card-header">
                Удаление клиента
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить? {{ object.full_name}}</p>
                <button type="submit"  class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'main:client_list'%}">Отмена</a>
            </div>
        </div>
    </form>


{% endblock %}

main/templates/main/client_detail.html
{% extends 'main/base.html' %}
{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">ФИО</th>
            <th scope="col">email</th>
            <th scope="col">Комментарий</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ object.full_name }}</td>
            <td>{{ object.email }}</td>
            <td>{{ object.comment }}</td>
            <td><a href="{% url 'main:client_update' object.pk %}">Изменить</a></td>
            <td><a href="{% url 'main:client_delete' object.pk %}">Удалить</a></td>
        </tr>
        </tbody>
    </table>

{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}


{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">Создать клиента {{ full_name }}</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
{#                        <input type="hidden" name="boat_id" value="{{ boat.pk }}">#}
                        {{ form.as_p }}
                        {% if object %}
                            <button type="submit"  class="btn btn-success">Изменить</button>
                        {% else %}
                            <button type="submit" class="btn btn-success">Создать</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}
{% block content %}
    {% if not user.is_staff %}
        <p class="d-inline-flex gap-1">
            <a class="btn btn-success" href="{% url 'main:create_client' %}">
                Добавить клиента
            </a>
        </p>
    {% endif %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ФИО</th>
            <th scope="col">email</th>
            <th scope="col">Комментарий</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>

                <th scope="row">{{ forloop.counter }}</th>

                {% if not user.is_staff %}
                    <td><a href="{% url 'main:client_detail' object.pk %}">{{ object.full_name }}</a></td>
                {% else %}
                    <td>{{ object.full_name }}</td>
                {% endif %}

                <td>{{ object.email }}</td>
                <td>{{ object.comment }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}


{% block content %}
    <div class="row text-center">

        <div class="col-6">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-3 text-bg-primary border-primary">
                    <h4 class="my-0 fw-normal">Клиенты</h4>
                </div>
                <div class="card-body">
                    {% if not user.is_authenticated %}
                        <h1 class="card-title pricing-card-title"><small
                                class="text-body-secondary fw-light">Тут будет кол-во ваших клиентов</small></h1>
                    {% elif user.is_staff %}

                        {% include 'main/includes/inc_manager_card_client.html' %}

                    {% else %}
                        <h1 class="card-title pricing-card-title"> {{ client_count }}<small
                                class="text-body-secondary fw-light"></small></h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Количество</li>
                            <li>Ваших клиентов</li>
                            <li>Которым возможно</li>
                            <li>сделать рассылку</li>
                        </ul>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <a href="{% url 'main:client_list' %}" type="button"
                           class="w-100 btn btn-lg btn-primary">Перейти</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-3 text-bg-primary border-primary">
                    <h4 class="my-0 fw-normal">Рассылки</h4>
                </div>
                <div class="card-body">
                    {% if not user.is_authenticated %}
                        <h1 class="card-title pricing-card-title"><small
                                class="text-body-secondary fw-light">Тут будет кол-во ваших Рассылок</small></h1>
                    {% elif user.is_staff %}

                        {% include 'main/includes/manager_cards.html' %}

                    {% else %}

                        <h1 class="card-title pricing-card-title"><small
                                class="text-body-secondary fw-light">{{ newsletter_count }}</small></h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Отчет:</li>
                            <li>Активные - {{ active_newsletters_count }}</li>
                            <li>Запланированные - {{ create_newsletters_count }}</li>
                            <li>Завершенные - {{ ended_newsletters_count }}</li>
                        </ul>
                        <a href="{% url 'main:newsletter_list' %}" type="button"
                           class="w-100 btn btn-lg btn-primary">К рассылкам</a>

                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% for blog in blog_list %}
        <div class="col-12">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-3 text-bg-primary border-primary">
                    <h4 class="my-0 fw-normal">{{ blog.title }}</h4>
                </div>
                <div class="card-body">
                    <img src="/media/{{ blog.image }}" alt="Card image app">
                    <p>{{ blog.content | truncatechars:300 }}</p>
                    <p>Количество просмотров - {{ blog.views }}</p>

                    <a href="{% url 'blog:blog_detail' blog.id %}" type="button"
                           class="w-100 btn btn-lg btn-primary">К статье</a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

main/templates/main/log_list.html
{% extends 'main/base.html' %}
{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Дата</th>
            <th scope="col">Статус попытки</th>
            <th scope="col">Ответ сервера</th>
            <th scope="col">Рассылка</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>

                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ object.date|date:'d.m.Y'}} {{object.date|time:'H:i' }}</td>
                <td>{{ object.status }}</td>
                <td>{{ object.answer }}</td>
                <td>{{ object.newsletter.name }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

main/templates/main/maildeliverysettings_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col">
            <div class="card-header">
                Удаление рассылки
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить? {{ object.name}}</p>
                <button type="submit"  class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'main:newsletter_list' %}">Отмена</a>
            </div>
        </div>
    </form>


{% endblock %}

main/templates/main/maildeliverysettings_detail.html
{% extends 'main/base.html' %}
{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название рассылки</th>
            <th scope="col">Начало</th>
            <th scope="col">Окончание</th>
            <th scope="col">Периодичность</th>
            <th scope="col">Тема письма</th>
            <th scope="col">Сообщение</th>
        </tr>
        </thead>
        <tbody>

        <tr>

            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ object.name }}</td>
            <td>{{ object.time_start }}</td>
            <td>{{ object.time_stop }}</td>
            <td>{{ object.periodicity }}</td>
            <td>{{ object.subject }}</td>
            <td>{{ object.message }}</td>
            {% if user == object.user %}
                <td><a href="{% url 'main:newsletter_update' object.pk %}">Изменить</a></td>
                <td><a href="{% url 'main:newsletter_delete' object.pk %}">Удалить</a></td>
            {% elif user.is_staff %}
                {% if object.status == 'Создана' %}
                    <td>
                        <a class="btn btn-danger"
                           href="{% url 'main:activate' object.pk %}">Отключить</a>
                    </td>
                {% elif object.status == 'Завершена' %}
                    <td>
                        <a class="btn btn-success"
                           href="{% url 'main:activate' object.pk %}">Включить</a>
                    </td>
                {% endif %}
            {% endif %}

        </tr>

        </tbody>
    </table>

{% endblock %}

main/templates/main/maildeliverysettings_form.html
{% extends 'main/base.html' %}


{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">Создать рассылку</div>
                <div class="card-body">
                    <form method="post" class="form-control">
                        {% csrf_token %}
{#                        <input type="hidden" name="boat_id" value="{{ boat.pk }}">#}
                        {{ form.as_p }}
                        {% if object %}
                            <button type="submit"  class="btn btn-success">Изменить</button>
                        {% else %}
                            <button type="submit" class="btn btn-success">Создать</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/maildeliverysettings_list.html
{% extends 'main/base.html' %}
{% block content %}
    {% if not user.is_staff %}
    <p class="d-inline-flex gap-1">
        <a class="btn btn-success" href="{% url 'main:newsletter_create' %}">
            Добавить рассылку
        </a>
    </p>
    {% endif %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название рассылки</th>
            <th scope="col">Сообщение</th>
            <th scope="col">Статус</th>
            {% if user.is_staff %}
                <th>Пользователь</th>
            {% endif %}
            <th scope="col">Логи</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>

                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'main:newsletter_detail' object.pk %}">{{ object.name }}</a></td>
                <td>{{ object.message }}</td>
                <td>{{ object.status }}</td>
                {% if user.is_staff %}
                    <td>{{ object.user }}</td>
                {% endif %}
                <td><a href="{% url 'main:log_list' object.pk %}">Логи</a></td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}